sudo: required
dist: trusty

language: node_js

node_js:
  - 6
  - 5
  - 4

os:
  - linux
  - osx

before_install:
  - npm install -g npm@latest

script:
  - ./node_modules/.bin/gulp ci

deploy:
  provider: npm
  email: piotr.baranowski@zaklinaczekodu.com
  api_key: $NPM_API_KEY
  on:
    node: 6
    condition: $TRAVIS_OS_NAME == linux
    tags: true
    repo: refilljs/refill-task-karma